import { FoodStall } from './types';

export const GENERATED_FOOD_STALLS: FoodStall[] = [
  // 1. SOVABAZAR / SHYAMBAZAR / NORTH KOLKATA
  {
    id: 'food-mitra-cafe',
    name: 'Mitra Cafe',
    bengaliName: 'মিত্র ক্যাফে',
    category: 'Heritage Cabin',
    famousDish: 'Diamond Fish Fry & Mutton Kabiraji',
    recommendedItems: [
      'Diamond Fish Fry',
      'Mutton Kabiraji Cutlet',
      'Brain Chop (Marrow)',
      'Fish Roll',
      'Pudina Chutney & Mustard Kashundi',
    ],
    description:
      'Established in 1910, Mitra Cafe is Kolkata’s premier heritage cabin. Every Durga Puja, thousands queue outside for its crispy egg-netted Mutton Kabiraji and pure Bhetki fish fry.',
    priceForTwo: '₹350 for two',
    latitude: 22.5976,
    longitude: 88.3698,
    nearestMetro: 'Shyambazar',
    nearestMetroWalkingM: 140,
    walkMinutes: 2,
    address: '47, Jatindra Mohan Ave, Sovabazar, Kolkata 700005',
    timings: '04:30 PM - 11:30 PM (All-Night on Puja days)',
    vibe: 'Iconic 1910 Heritage • All-Night Festive Rush',
  },
  {
    id: 'food-golbari',
    name: 'Golbari (New Punjabi Hotel)',
    bengaliName: 'গোলবাড়ি',
    category: 'Bengali Cuisine',
    famousDish: 'Kosha Mangsho with Paratha',
    recommendedItems: [
      'Slow-Cooked Kosha Mangsho (Dark Gravy Mutton)',
      'Triangular Plain Parathas',
      'Sliced Onions & Green Chilies',
    ],
    description:
      'Over 98 years old at Shyambazar 5-point crossing, Golbari is world-famous for its pitch-black, intensely spiced, melt-in-the-mouth slow-cooked Mutton Kosha.',
    priceForTwo: '₹450 for two',
    latitude: 22.6025,
    longitude: 88.3718,
    nearestMetro: 'Shyambazar',
    nearestMetroWalkingM: 110,
    walkMinutes: 2,
    address: 'Acharya Prafulla Chandra Rd, Fariapukur, Shyambazar, Kolkata 700004',
    timings: '12:30 PM - 11:00 PM',
    vibe: 'Legendary Kosha Mangsho Destination • Nostalgic & Smoky',
  },
  {
    id: 'food-dhiren-cabin',
    name: 'Dhiren Cabin',
    bengaliName: 'ধীরেন কেবিন',
    category: 'Heritage Cabin',
    famousDish: 'Prawn Cutlet & Fish Kabiraji',
    recommendedItems: [
      'Gold Prawn Cutlet',
      'Fish Diamond Fry',
      'Mutton Kabiraji',
      'Steaming Darjeeling Tea',
    ],
    description:
      'A century-old North Kolkata institution beside Sovabazar Rajbari. Frequented by generations of cinema legends and nocturnal Durga Puja revelers for crisp crumb-fried cutlets.',
    priceForTwo: '₹280 for two',
    latitude: 22.5979,
    longitude: 88.3672,
    nearestMetro: 'Sovabazar Sutanuti',
    nearestMetroWalkingM: 190,
    walkMinutes: 3,
    address: 'Sovabazar St, near Shobhabazar Rajbari, Kolkata 700005',
    timings: '04:00 PM - 10:30 PM',
    vibe: 'Centenary Rajbari Heritage Cabin',
  },
  {
    id: 'food-allen-kitchen',
    name: 'Allen Kitchen',
    bengaliName: 'অ্যালেন কিচেন',
    category: 'Heritage Cabin',
    famousDish: 'Pure Ghee Prawn Cutlet',
    recommendedItems: [
      'Special Prawn Cutlet (Fried in Pure Ghee)',
      'Bhetki Fish Roll',
      'Mutton Steak Fry',
    ],
    description:
      'Founded in 1884, Allen Kitchen is renowned across Bengal for frying its jumbo prawn cutlets and cutlets exclusively in fragrant pure desi cow ghee rather than oil.',
    priceForTwo: '₹400 for two',
    latitude: 22.5988,
    longitude: 88.3685,
    nearestMetro: 'Shyambazar',
    nearestMetroWalkingM: 260,
    walkMinutes: 3,
    address: '40/1, Jatindra Mohan Ave, Sovabazar, Kolkata 700006',
    timings: '04:30 PM - 10:30 PM',
    vibe: 'Pure Ghee Scottish-Bengali Heritage since 1884',
  },
  {
    id: 'food-paramount',
    name: 'Paramount Cold Drinks',
    bengaliName: 'প্যারামাউন্ট',
    category: 'Cafe & Snacks',
    famousDish: 'Daab Sherbet & Passion Fruit',
    recommendedItems: [
      'Signature Daab Sherbet (Green Coconut with Malai)',
      'Passion Fruit Sherbet',
      'Tamarind (Kacha Aam) Sherbet',
      'Vanilla Malai Sherbet',
    ],
    description:
      'Operating since 1918 near College Square, this historic sherbet joint hosted Netaji Subhas Chandra Bose and freedom fighters. Its tender green coconut Daab Sherbet is the ultimate thirst-quencher during pandal hopping.',
    priceForTwo: '₹180 for two',
    latitude: 22.5768,
    longitude: 88.3638,
    nearestMetro: 'Mahatma Gandhi Road',
    nearestMetroWalkingM: 350,
    walkMinutes: 4,
    address: '1/1/1D, Bankim Chatterjee St, College Square, Kolkata 700073',
    timings: '11:00 AM - 10:00 PM',
    vibe: 'Freedom Movement Historical Sherbet Den since 1918',
  },
  {
    id: 'food-putiram',
    name: 'Putiram Sweets',
    bengaliName: 'পুঁটিরাম',
    category: 'Mishti & Desserts',
    famousDish: 'Radhaballabhi with Cholar Dal',
    recommendedItems: [
      'Stuffed Radhaballabhi with Hing & Urad Dal',
      'Sweet & Savory Cholar Dal with Coconut bits',
      'Kesar Jalebi (Ghee Fried)',
      'Abar Khabo Sandesh',
      'Malpoa',
    ],
    description:
      'College Street’s crown jewel for breakfast and evening savories. The hot, fluffy Radhaballabhi paired with rich, coconut-topped Cholar Dal is the definitive Puja morning tradition.',
    priceForTwo: '₹150 for two',
    latitude: 22.5746,
    longitude: 88.3635,
    nearestMetro: 'Central',
    nearestMetroWalkingM: 380,
    walkMinutes: 5,
    address: '12A, Surya Sen St, College Square, Kolkata 700012',
    timings: '07:00 AM - 09:30 PM',
    vibe: 'Quintessential College Street Mishti & Kochuri Heritage',
  },
  {
    id: 'food-kalika',
    name: 'Kalika Mukhorochok Telebhaja',
    bengaliName: 'কালিকা মুখরোচক তেলেভাজা',
    category: 'Street Food & Chaat',
    famousDish: 'Fish Finger, Mochar Chop & Beguni',
    recommendedItems: [
      'Calcutta Bhetki Fish Finger',
      'Mochar Chop (Banana Flower Cutlet)',
      'Crispy Beguni (Fried Eggplant)',
      'Alur Chop with Muri (Puffed Rice)',
    ],
    description:
      'The legendary telebhaja (fritter) shop of College Street since 1965. Expect hot, fresh artisanal chops served on sal leaves with chopped rock salt and puffed rice.',
    priceForTwo: '₹120 for two',
    latitude: 22.5781,
    longitude: 88.3644,
    nearestMetro: 'Mahatma Gandhi Road',
    nearestMetroWalkingM: 280,
    walkMinutes: 3,
    address: '29, Surya Sen St, College Street, Kolkata 700009',
    timings: '04:00 PM - 09:30 PM',
    vibe: 'Legendary Evening Telebhaja Stall',
  },
  {
    id: 'food-nakur',
    name: 'Girish Chandra Dey & Nakur Chandra Nandy',
    bengaliName: 'গিরিশ চন্দ্র দে ও নকুড় চন্দ্র নন্দী',
    category: 'Mishti & Desserts',
    famousDish: 'Jolbhora Talsash Sandesh',
    recommendedItems: [
      'Jolbhora Talsash (Liquid Nolen Gur filled Sandesh)',
      'Parijat Sandesh',
      'Chocolate Fudge Sandesh',
      'Malai Roll',
      'Mousumi Sandesh',
    ],
    description:
      'Established in 1844 near Hedua Park. Celebrated as Kolkata’s supreme artisanal sandesh masters, where master confectioners craft delicate curd-based sweets with liquid date palm jaggery centers.',
    priceForTwo: '₹200 for two',
    latitude: 22.5898,
    longitude: 88.3688,
    nearestMetro: 'Girish Park',
    nearestMetroWalkingM: 380,
    walkMinutes: 5,
    address: '56, Ramdulal Sarkar St, Hedua, Kolkata 700006',
    timings: '07:00 AM - 10:00 PM',
    vibe: '1844 Royal Sandesh Confectionery',
  },
  {
    id: 'food-nobin-das',
    name: 'Nobin Chandra Das & Sons',
    bengaliName: 'নবীন চন্দ্র দাস',
    category: 'Mishti & Desserts',
    famousDish: 'Original Spongy White Rosogolla',
    recommendedItems: [
      'The Original 1868 Spongy Rosogolla',
      'Abar Khabo Sandesh',
      'Kacha Golla',
      'Rasmalai',
    ],
    description:
      'Nobin Chandra Das invented the world-famous spongy Bengali Rosogolla in 1868 right here in Baghbazar. A pilgrimage spot for authentic, melt-in-the-mouth syrupy chenna balls.',
    priceForTwo: '₹160 for two',
    latitude: 22.5997,
    longitude: 88.3659,
    nearestMetro: 'Sovabazar Sutanuti',
    nearestMetroWalkingM: 320,
    walkMinutes: 4,
    address: '169, Rabindra Sarani, Sovabazar, Kolkata 700005',
    timings: '08:00 AM - 09:30 PM',
    vibe: 'Birthplace of the Bengali Rosogolla',
  },
  {
    id: 'food-chittaranjan-sweets',
    name: 'Chittaranjan Mistanna Bhandar',
    bengaliName: 'চিত্তরঞ্জন মিষ্টান্ন ভাণ্ডার',
    category: 'Mishti & Desserts',
    famousDish: 'Madhuparka & White Spongy Rosogolla',
    recommendedItems: [
      'Steaming Hot Rosogolla',
      'Madhuparka (Honey Curd Elixir)',
      'Malai Sandesh',
    ],
    description:
      'Famous across North Kolkata for serving the lightest, juiciest piping-hot rosogollas straight from boiling copper cauldrons during Puja nights.',
    priceForTwo: '₹180 for two',
    latitude: 22.5985,
    longitude: 88.3678,
    nearestMetro: 'Shyambazar',
    nearestMetroWalkingM: 280,
    walkMinutes: 3,
    address: '34B, Shyamaprosad Mukherjee Rd, Sovabazar, Kolkata 700006',
    timings: '07:30 AM - 10:00 PM',
    vibe: 'Piping Hot Copper-Vessel Rosogolla Heritage',
  },
  {
    id: 'food-royal-indian',
    name: 'Royal Indian Hotel',
    bengaliName: 'রয়্যাল ইন্ডিয়ান হোটেল',
    category: 'Mughlai & Biryani',
    famousDish: 'Royal Mutton Biryani (Traditional No-Potato) & Pasinda',
    recommendedItems: [
      'Royal Shahi Mutton Biryani',
      'Mutton Pasinda Kebab',
      'Shahi Mutton Chaap',
      'Firni with Silver Leaf',
    ],
    description:
      'Founded in 1905 opposite Nakhoda Masjid by descendants of Awadhi royal chefs. Famous for its authentic royal Awadhi biryani cooked strictly without potato, emphasizing rich saffron and pure ghee aroma.',
    priceForTwo: '₹550 for two',
    latitude: 22.5832,
    longitude: 88.3564,
    nearestMetro: 'Mahatma Gandhi Road',
    nearestMetroWalkingM: 450,
    walkMinutes: 6,
    address: '147, Rabindra Sarani, Bara Bazar, Kolkata 700073',
    timings: '11:00 AM - 11:30 PM',
    vibe: 'Centenary Awadhi Royal Heritage since 1905',
  },

  // 2. CENTRAL / ESPLANADE / CHANDNI CHOWK
  {
    id: 'food-nizams',
    name: "Nizam's",
    bengaliName: 'নিজামস',
    category: 'Kathi Rolls',
    famousDish: 'The Original Kathi Roll',
    recommendedItems: [
      'Double Mutton Egg Kathi Roll',
      'Chicken Kathi Roll wrapped in Paratha',
      'Mutton Boti Kebab',
      'Beef/Mutton Seekh Kebab',
    ],
    description:
      'The birthplace of the Kathi Roll in 1932. Skewered kebabs wrapped in flaky, egg-layered parathas with lemon, raw onions, and green chilies. The ultimate grab-and-go snack for Durga Puja hoppers.',
    priceForTwo: '₹300 for two',
    latitude: 22.5606,
    longitude: 88.3533,
    nearestMetro: 'Esplanade',
    nearestMetroWalkingM: 280,
    walkMinutes: 3,
    address: '21, 22, Hogg St, New Market Area, Kolkata 700087',
    timings: '11:30 AM - 11:00 PM',
    vibe: 'The World’s First Kathi Roll Pioneer',
  },
  {
    id: 'food-chitto-da',
    name: "Chitto Da's Dokan (Dacres Lane)",
    bengaliName: 'চিত্তদার দোকান (ডেকার্স লেন)',
    category: 'Street Food & Chaat',
    famousDish: 'Chicken Stew with Butter Toast & Fish Roll',
    recommendedItems: [
      'Peppery Herbal Chicken Stew with Vegetables',
      'Thick Butter-Toasted Pawnbread',
      'Diamond Bhetki Fish Roll',
      'Mutton Khichdi (Puja Special)',
    ],
    description:
      'Dacres Lane (James Hickey Sarani) is Kolkata’s premier historic food alley. Chitto Da’s piping hot, non-spicy vegetable and chicken stew served with crusty butter toast has nourished Kolkata for over 70 years.',
    priceForTwo: '₹220 for two',
    latitude: 22.5684,
    longitude: 88.3512,
    nearestMetro: 'Esplanade',
    nearestMetroWalkingM: 220,
    walkMinutes: 3,
    address: 'Dacres Lane, Peerless Inn Lane, Esplanade, Kolkata 700069',
    timings: '07:00 AM - 09:30 PM',
    vibe: 'Kolkata’s Most Famous Heritage Food Alley',
  },
  {
    id: 'food-anadi-cabin',
    name: 'Anadi Cabin',
    bengaliName: 'অনাদি কেবিন',
    category: 'Heritage Cabin',
    famousDish: 'Mughlai Paratha with Dry Aloo Kasha',
    recommendedItems: [
      'Special Double Duck Egg Mughlai Paratha',
      'Mutton Keema stuffed Mughlai Paratha',
      'Dry Aloo Torkari & Raw Onion Salad',
    ],
    description:
      'Established in 1925, Anadi Cabin perfected the Calcutta-style Mughlai Paratha: crisp deep-fried square pastry stuffed with minced meat, duck eggs, and onions, served with spicy dry aloo curry.',
    priceForTwo: '₹250 for two',
    latitude: 22.5638,
    longitude: 88.3529,
    nearestMetro: 'Esplanade',
    nearestMetroWalkingM: 290,
    walkMinutes: 4,
    address: '9, Jawaharlal Nehru Rd, New Market Area, Dharmatala, Kolkata 700013',
    timings: '12:00 PM - 09:30 PM',
    vibe: '1925 Legendary Mughlai Paratha Cabin',
  },
  {
    id: 'food-aminia-esplanade',
    name: 'Aminia (Esplanade Flagship)',
    bengaliName: 'আমিনিয়া',
    category: 'Mughlai & Biryani',
    famousDish: 'Special Awadhi Mutton Biryani & Rezala',
    recommendedItems: [
      'Special Mutton Biryani with Egg & Potato',
      'Mutton Rezala (Fragrant White Yoghurt Gravy)',
      'Chicken Chaap',
      'Shahi Tukda',
    ],
    description:
      'Founded in 1929 next to the Nakhoda Mosque and Sir Stuart Hogg Market, Aminia is an inseparable part of every Kolkata Durga Puja festive feast.',
    priceForTwo: '₹550 for two',
    latitude: 22.5631,
    longitude: 88.3538,
    nearestMetro: 'Esplanade',
    nearestMetroWalkingM: 240,
    walkMinutes: 3,
    address: '6A, S.N. Banerjee Road, New Market, Kolkata 700087',
    timings: '11:00 AM - 11:30 PM',
    vibe: '1929 Grand Calcutta Biryani Institution',
  },
  {
    id: 'food-kc-das',
    name: 'K.C. Das (Esplanade)',
    bengaliName: 'কে.সি. দাশ',
    category: 'Mishti & Desserts',
    famousDish: 'Canned & Fresh Spongy Rossogolla',
    recommendedItems: [
      'Signature Rossogolla',
      'Rossomalai in Sweet Cardamom Milk',
      'Amrita Kumbha',
      'Gulab Jamun',
    ],
    description:
      'Stationed at Esplanade crossing since 1930, Krishna Chandra Das commercialized vacuum-packed rasgullas and invented Rossomalai in 1930.',
    priceForTwo: '₹180 for two',
    latitude: 22.5645,
    longitude: 88.3519,
    nearestMetro: 'Esplanade',
    nearestMetroWalkingM: 80,
    walkMinutes: 1,
    address: '11A, Esplanade East, Chowringhee, Kolkata 700069',
    timings: '08:00 AM - 09:30 PM',
    vibe: 'Esplanade Landmark Confectioner since 1930',
  },
  {
    id: 'food-bhim-chandra-nag',
    name: 'Bhim Chandra Nag',
    bengaliName: 'ভীম চন্দ্র নাগ',
    category: 'Mishti & Desserts',
    famousDish: 'Lady Canning (Ledikeni) & Jolbhora Sandesh',
    recommendedItems: [
      'Original Ledikeni (created for Lady Canning in 1858)',
      'Abar Khabo Sandesh',
      'Manohara (Curd Ball in Sugar Shell)',
      'Kancha Golla',
    ],
    description:
      'Founded in 1826 at Bowbazar. Confectioner Bhim Nag personally crafted the famous Ledikeni sweet to honor Lady Canning during British India. A true living sweet museum.',
    priceForTwo: '₹190 for two',
    latitude: 22.5702,
    longitude: 88.3611,
    nearestMetro: 'Central',
    nearestMetroWalkingM: 320,
    walkMinutes: 4,
    address: '5, Nirmal Chandra St, Bowbazar, Kolkata 700012',
    timings: '08:00 AM - 09:30 PM',
    vibe: '1826 Living Bengali Sweet Museum',
  },

  // 3. PARK STREET & RABINDRA SADAN
  {
    id: 'food-peter-cat',
    name: 'Peter Cat',
    bengaliName: 'পিটার ক্যাট',
    category: 'Cafe & Snacks',
    famousDish: 'Chelo Kebab Platter with Butter & Egg',
    recommendedItems: [
      'Iconic Chelo Kebab (Butter Rice, Grilled Tomato, Fried Egg, Mutton Seekh, Chicken Kebab)',
      'Chicken Marghi',
      'Fish Makhmali',
      'Cocktails & Beer',
    ],
    description:
      'Kolkata’s most revered culinary landmark on Park Street. The sizzle of butter melting over basmati rice and charcoal-grilled Iranian-style seekh kebabs draws lines around the block every Puja night.',
    priceForTwo: '₹1,100 for two',
    latitude: 22.5518,
    longitude: 88.3536,
    nearestMetro: 'Park Street',
    nearestMetroWalkingM: 320,
    walkMinutes: 4,
    address: '18A, Park Street, Park Street Area, Kolkata 700016',
    timings: '12:00 PM - 11:30 PM',
    vibe: 'Park Street Colonial Fine Dining & Vintage Glow',
  },
  {
    id: 'food-kusum-rolls',
    name: 'Kusum Rolls',
    bengaliName: 'কুসুম রোলস',
    category: 'Kathi Rolls',
    famousDish: 'Double Egg Double Chicken Roll',
    recommendedItems: [
      'Double Egg Double Chicken Roll',
      'Cheese Chicken Kathi Roll',
      'Mutton Liver (Kaleji) Roll',
      'Paneer Tikka Roll',
    ],
    description:
      'Park Street’s beloved roadside roll window. Famous for its thick, crispy laccha parathas fried with eggs, stuffed generously with spiced tandoori chicken bits and zesty sauces.',
    priceForTwo: '₹220 for two',
    latitude: 22.5515,
    longitude: 88.3538,
    nearestMetro: 'Park Street',
    nearestMetroWalkingM: 300,
    walkMinutes: 3,
    address: '21, Karnani Mansion, Park Street, Kolkata 700016',
    timings: '11:00 AM - 11:30 PM',
    vibe: 'Bustling Park Street Late-Night Roll Counter',
  },
  {
    id: 'food-flurys',
    name: 'Flurys',
    bengaliName: 'ফ্লুরিজ',
    category: 'Cafe & Snacks',
    famousDish: 'English Breakfast, Rum Balls & Chocolate Boat',
    recommendedItems: [
      'Rich Dark Rum Balls',
      'Chocolate Boat Pastry',
      'Full English Breakfast with Sausages & Hashbrowns',
      'Darjeeling Single Estate Tea',
      'Chicken Patty',
    ],
    description:
      'The legendary tearoom of Kolkata established in 1927. Renowned for its Viennese pastries, festive confectionery, and nostalgic colonial atmosphere on Park Street.',
    priceForTwo: '₹750 for two',
    latitude: 22.5524,
    longitude: 88.3524,
    nearestMetro: 'Park Street',
    nearestMetroWalkingM: 220,
    walkMinutes: 3,
    address: '18, Park Street, Park Street Area, Kolkata 700071',
    timings: '07:30 AM - 11:00 PM',
    vibe: '1927 European Tearoom & Confectionery Glamour',
  },
  {
    id: 'food-mocambo',
    name: 'Mocambo',
    bengaliName: 'মোকাম্বো',
    category: 'Cafe & Snacks',
    famousDish: 'Devilled Crab & Chicken Tetrazzini',
    recommendedItems: [
      'Baked Devilled Crab in shell',
      'Chicken Tetrazzini with au gratin cheese',
      'Fish Florentine',
      'Chateaubriand Steak',
    ],
    description:
      'Established in 1956, Mocambo brought fine European continental dining to Kolkata. Its baked crab served directly in the crab shell remains unmatched.',
    priceForTwo: '₹1,200 for two',
    latitude: 22.5529,
    longitude: 88.3522,
    nearestMetro: 'Park Street',
    nearestMetroWalkingM: 200,
    walkMinutes: 2,
    address: '25B, Park Street, Taltala, Kolkata 700016',
    timings: '11:30 AM - 11:00 PM',
    vibe: '1956 Mid-Century Continental Elegance',
  },
  {
    id: 'food-arsalan-park-circus',
    name: 'Arsalan (Park Circus 7-Point)',
    bengaliName: 'আরসালান',
    category: 'Mughlai & Biryani',
    famousDish: 'Kolkata Special Mutton Biryani & Chaap',
    recommendedItems: [
      'Arsalan Special Mutton Biryani (2 succulent meat pieces + potato)',
      'Chicken Chaap in Rich Poppy & Ghee Gravy',
      'Mutton Galawati Kebab',
      'Firni with Kewra Essence',
    ],
    description:
      'Synonymous with Kolkata’s fragrant, light, saffron-infused biryani featuring tender mutton and the beloved boiled potato. During Puja, Arsalan churns out hundreds of handis every hour.',
    priceForTwo: '₹650 for two',
    latitude: 22.5418,
    longitude: 88.3664,
    nearestMetro: 'Rabindra Sadan',
    nearestMetroWalkingM: 850,
    walkMinutes: 10,
    address: '191, Marina Garden Court, Park Circus 7-Point, Kolkata 700017',
    timings: '11:00 AM - 12:30 AM',
    vibe: 'Kolkata’s Biryani Titan • Festive Saffron Aroma',
  },
  {
    id: 'food-shiraz',
    name: 'Shiraz Golden Restaurant',
    bengaliName: 'শিরাজ গোল্ডেন রেস্তোরাঁ',
    category: 'Mughlai & Biryani',
    famousDish: 'Shahi Mutton Biryani & Mutton Chaap',
    recommendedItems: [
      'Shahi Mutton Awadhi Biryani',
      'Shiraz Special Mutton Chaap',
      'Mutton Kasha',
      'Rumali Roti',
    ],
    description:
      'Serving golden-era Mughlai flavors since 1941 at Mullick Bazar. Beloved for its gentle yet deeply aromatic spices and impeccably cooked tender mutton.',
    priceForTwo: '₹550 for two',
    latitude: 22.5469,
    longitude: 88.3615,
    nearestMetro: 'Rabindra Sadan',
    nearestMetroWalkingM: 700,
    walkMinutes: 8,
    address: '135, Mother Teresa Sarani, Mullick Bazar, Kolkata 700014',
    timings: '11:30 AM - 11:30 PM',
    vibe: '1941 Mughlai Heritage • Traditional Royal Flavors',
  },

  // 4. SOUTH KOLKATA / BHOWANIPORE / JATIN DAS PARK / KALIGHAT / GARIAHAT
  {
    id: 'food-balaram-mullick',
    name: 'Balaram Mullick & Radharaman Mullick',
    bengaliName: 'বলরাম মল্লিক ও রাধারমণ মল্লিক',
    category: 'Mishti & Desserts',
    famousDish: 'Baked Rosogolla & Nolen Gur Souffle',
    recommendedItems: [
      'Warm Baked Rosogolla (Caramelized Crust)',
      'Nolen Gur Souffle',
      'Mango Gelato Sandesh',
      'Jolbhora Kacha Golla',
      'Shor Bhaja',
    ],
    description:
      'Founded in 1885 in Bhowanipore. Balaram Mullick transformed modern Bengali confectionery by pioneering the baked rosogolla, fusion souffles, and artisanal seasonal mishti.',
    priceForTwo: '₹220 for two',
    latitude: 22.5312,
    longitude: 88.3496,
    nearestMetro: 'Netaji Bhavan',
    nearestMetroWalkingM: 260,
    walkMinutes: 3,
    address: '2, Paddapukur Rd, Jadubabur Bazar, Bhowanipore, Kolkata 700020',
    timings: '07:00 AM - 10:30 PM',
    vibe: 'Modern Master Confectioner since 1885',
  },
  {
    id: 'food-maharaja-maharani',
    name: 'Maharaja Kochuri & Maharani Tea',
    bengaliName: 'মহারাজা কচুরি ও মহারানী চা',
    category: 'Street Food & Chaat',
    famousDish: 'Hing Kochuri with Chholar Dal & Jalebi',
    recommendedItems: [
      'Crispy Hing Kochuri (Asafoetida Infused)',
      'Sweet-Spicy Aloo Torkari with Green Peas',
      'Syrupy Crisp Jalebi',
      'Kesar Kulhad Chai (Clay Cup Tea)',
    ],
    description:
      'Sitting directly across Sarat Bose Road near Deshapriya Park, Maharaja and Maharani are sister stalls where thousands of morning and evening Puja hoppers gather for hot kochuris and clay-cup tea.',
    priceForTwo: '₹120 for two',
    latitude: 22.5186,
    longitude: 88.3542,
    nearestMetro: 'Jatin Das Park',
    nearestMetroWalkingM: 420,
    walkMinutes: 5,
    address: '152, Sarat Bose Rd, Manoharpukur, Kalighat, Kolkata 700029',
    timings: '06:30 AM - 12:00 PM, 04:00 PM - 09:30 PM',
    vibe: 'The Definitive South Kolkata Puja Morning Breakfast',
  },
  {
    id: 'food-campari',
    name: 'Campari',
    bengaliName: 'ক্যাম্পারি',
    category: 'Heritage Cabin',
    famousDish: 'Fish Roll & Chicken Cutlet',
    recommendedItems: [
      'Signature Bhetki Fish Roll',
      'Crisp Chicken Cutlet',
      'Mutton Pantheras',
      'Prawn Cutlet',
      'Bengali Mustard Kashundi Dip',
    ],
    description:
      'South Kolkata’s most famous snack counter at Gariahat, operational since 1979. Their signature Fish Roll wrapped around spiced mince and fried golden brown is legendary.',
    priceForTwo: '₹260 for two',
    latitude: 22.5182,
    longitude: 88.3656,
    nearestMetro: 'Kalighat',
    nearestMetroWalkingM: 780,
    walkMinutes: 9,
    address: '155B, Rash Behari Ave, Gariahat, Kolkata 700029',
    timings: '04:00 PM - 09:30 PM',
    vibe: 'Gariahat’s Beloved Evening Cutlet Counter',
  },
  {
    id: 'food-apanjan',
    name: 'Apanjan',
    bengaliName: 'আপনজন',
    category: 'Heritage Cabin',
    famousDish: 'Devilled Crab & Fish Fry',
    recommendedItems: [
      'Stuffed Devilled Crab (Crab Meat in Spiced Shell)',
      'Diamond Bhetki Fish Fry',
      'Mutton Kabiraji',
      'Brain Chop',
    ],
    description:
      'A legendary hidden gem tucked into Sadananda Road near Kalighat Metro. Its artisanal Devilled Crab and colossal Bhetki Fish Fry fried in refined oil draw foodies from all over the world.',
    priceForTwo: '₹340 for two',
    latitude: 22.5222,
    longitude: 88.3475,
    nearestMetro: 'Kalighat',
    nearestMetroWalkingM: 180,
    walkMinutes: 2,
    address: '50, Sadananda Rd, Anami Sangha, Kalighat, Kolkata 700026',
    timings: '04:30 PM - 10:00 PM',
    vibe: 'Kalighat Devilled Crab & Fish Fry Legend',
  },
  {
    id: 'food-bedwin',
    name: 'Bedwin',
    bengaliName: 'বেডউইন',
    category: 'Kathi Rolls',
    famousDish: 'Mutton Tikka Roll & Chicken Kebab',
    recommendedItems: [
      'Mutton Tikka Kathi Roll',
      'Double Egg Chicken Roll',
      'Tandoori Chicken Quarter',
      'Biryani Handi',
    ],
    description:
      'Gariahat’s go-to pitstop during evening Puja shopping and pandal hopping around Ekdalia Evergreen and Singhi Park. Deliciously charred rolls with fresh spices.',
    priceForTwo: '₹280 for two',
    latitude: 22.5191,
    longitude: 88.3651,
    nearestMetro: 'Kalighat',
    nearestMetroWalkingM: 800,
    walkMinutes: 9,
    address: '157C, Rash Behari Ave, Gariahat, Kolkata 700019',
    timings: '12:00 PM - 11:00 PM',
    vibe: 'Gariahat Shopping District Roll Hub',
  },
  {
    id: 'food-bhojohori-manna',
    name: 'Bhojohori Manna (Hindustan Park)',
    bengaliName: 'ভজহরি মান্না',
    category: 'Bengali Cuisine',
    famousDish: 'Daab Chingri & Bhetki Paturi',
    recommendedItems: [
      'Daab Chingri (Prawns in Tender Coconut Shell)',
      'Bhetki Paturi wrapped in Banana Leaf',
      'Kosha Mangsho with Luchi',
      'Chitol Muitha',
      'Nolen Gur Payesh',
    ],
    description:
      'Named after the famous Manna Dey song, Bhojohori Manna celebrates authentic homestyle Bengali culinary heirlooms. Perfect festive sit-down meal while hopping around South Kolkata pujas.',
    priceForTwo: '₹600 for two',
    latitude: 22.5178,
    longitude: 88.3621,
    nearestMetro: 'Kalighat',
    nearestMetroWalkingM: 650,
    walkMinutes: 7,
    address: '18/1A, Hindustan Rd, Hindustan Park, Gariahat, Kolkata 700029',
    timings: '12:00 PM - 10:30 PM',
    vibe: 'Traditional Bengali Festive Dining & Homestyle Flavors',
  },
  {
    id: 'food-blue-poppy',
    name: 'The Blue Poppy (Thakali)',
    bengaliName: 'ব্লু পপি',
    category: 'Cafe & Snacks',
    famousDish: 'Kothey Momos & Thukpa',
    recommendedItems: [
      'Pan-Fried Pork / Chicken Kothey Momos',
      'Steamed Tingmo with Doma Chilli Chicken',
      'Spicy Tibetan Thukpa Noodle Soup',
      'Shaphalay (Fried Meat Pie)',
    ],
    description:
      'Kolkata’s undisputed queen of momos, curated by Doma Wang. Light, pillowy momos stuffed with juicy minced meats and paired with fiery house-made tomato-sesame-chilli sauce.',
    priceForTwo: '₹400 for two',
    latitude: 22.5362,
    longitude: 88.3512,
    nearestMetro: 'Netaji Bhavan',
    nearestMetroWalkingM: 320,
    walkMinutes: 4,
    address: 'Sikkim House, 4/1, Middleton St / Elgin Rd, Kolkata 700071',
    timings: '12:00 PM - 09:30 PM',
    vibe: 'Kolkata’s Most Famous Authentic Tibetan Momo Haven',
  },

  // 5. EAST KOLKATA / SALT LAKE / SECTOR V
  {
    id: 'food-oudh-salt-lake',
    name: 'Oudh 1590 (Salt Lake)',
    bengaliName: 'অবধ ১৫৯০',
    category: 'Mughlai & Biryani',
    famousDish: 'Awadhi Handi Biryani & Galawati Kebab',
    recommendedItems: [
      'Raan Biryani',
      'Melt-in-Mouth Galawati Kebab with Ulte Tawe Ka Paratha',
      'Murgh Parda Biryani',
      'Shahi Tukda with Rabdi',
    ],
    description:
      'Period-dining Awadhi culinary retreat near Salt Lake City Centre. Rich slow-cooked dum handi biryanis and royal kebabs recreating the Lucknow court of Nawab Wajid Ali Shah.',
    priceForTwo: '₹850 for two',
    latitude: 22.5878,
    longitude: 88.4089,
    nearestMetro: 'City Centre',
    nearestMetroWalkingM: 280,
    walkMinutes: 3,
    address: 'CJ 243, Sector 2, Salt Lake, Kolkata 700091',
    timings: '12:00 PM - 10:30 PM',
    vibe: 'Royal Awadhi Court Dining & Scented Dum Biryanis',
  },
  {
    id: 'food-gupta-brothers',
    name: 'Gupta Brothers (City Centre 1)',
    bengaliName: 'গুপ্ত ব্রাদার্স',
    category: 'Street Food & Chaat',
    famousDish: 'Kachori Sabzi, Pav Bhaji & Rajbhog',
    recommendedItems: [
      'Club Kachori with Aloo Sabzi',
      'Special Butter Pav Bhaji',
      'Spongy Kesar Rajbhog',
      'Dahi Vada with Sweet Tamarind Chutney',
    ],
    description:
      'The top vegetarian and chaat destination for hoppers visiting Salt Lake pujas (FD Block, BJ Block, AK Block). Quick, pristine, and comforting festive bites.',
    priceForTwo: '₹250 for two',
    latitude: 22.5892,
    longitude: 88.4095,
    nearestMetro: 'City Centre',
    nearestMetroWalkingM: 190,
    walkMinutes: 2,
    address: 'Block DC, Sector 1, Salt Lake City, Kolkata 700064',
    timings: '08:00 AM - 10:30 PM',
    vibe: 'Crispy Kachoris, Royal Sweets & Chaat Counter',
  },

  // 6. HOWRAH MAIDAN
  {
    id: 'food-golapi-howrah',
    name: 'Golapi (Howrah Maidan)',
    bengaliName: 'গোলাপি',
    category: 'Street Food & Chaat',
    famousDish: 'Radhaballabhi & Hot Jalebi',
    recommendedItems: [
      'Radhaballabhi with Cholar Dal',
      'Stuffed Samosa (Singara)',
      'Crisp Syrup Jalebi',
      'Pantua',
    ],
    description:
      'Howrah’s most beloved 80-year-old street snack stall just outside Howrah Maidan Metro Station. Perfect first pitstop when crossing under the river via Green Line.',
    priceForTwo: '₹100 for two',
    latitude: 22.5861,
    longitude: 88.3341,
    nearestMetro: 'Howrah Maidan',
    nearestMetroWalkingM: 120,
    walkMinutes: 2,
    address: 'G.T. Road, near Howrah Maidan Metro, Howrah 711101',
    timings: '06:30 AM - 10:00 PM',
    vibe: 'Heritage Howrah Street Food Legend',
  },
];
